# Generated by Django 4.2.26 on 2025-11-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0002_remove_siswa_id_alter_siswa_nis'),
        ('admin_app', '0003_pegawai_gaji_pokok_alter_pegawai_id_pegawai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siswa', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('nilai_mapel', models.JSONField()),
                ('rata_rata', models.FloatField()),
                ('predikat', models.CharField(max_length=5)),
                ('keterangan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum Lunas')], max_length=10)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pegawai', models.CharField(blank=True, max_length=255)),
                ('gaji_pokok', models.PositiveIntegerField(default=0)),
                ('tunjangan_jabatan', models.PositiveIntegerField(default=0)),
                ('keterangan_tunjangan', models.CharField(blank=True, max_length=255, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.pegawai')),
            ],
        ),
    ]
