# Generated by Django 4.2.26 on 2025-11-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(choices=[('guru', 'Guru'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
                ('gaji_pokok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siswa', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('nilai_mapel', models.JSONField()),
                ('rata_rata', models.FloatField()),
                ('predikat', models.CharField(max_length=5)),
                ('keterangan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siswa', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('bulan', models.CharField(max_length=20)),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunjangan', models.IntegerField(default=0)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.pegawai')),
            ],
        ),
    ]
