# Generated by Django 4.2.26 on 2025-11-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_pegawai_gaji_pokok_alter_pegawai_id_pegawai'),
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaji',
            old_name='tunjangan',
            new_name='gaji_pokok',
        ),
        migrations.AddField(
            model_name='gaji',
            name='keterangan_tunjangan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gaji',
            name='tunjangan_jabatan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaji', to='admin_app.pegawai'),
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
