# Generated by Django 4.2.26 on 2025-11-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spp',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spp',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
