# Generated by Django 4.2.26 on 2025-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('gaji_pokok', models.IntegerField()),
                ('tunjangan', models.IntegerField(default=0)),
                ('total_gaji', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GajiGuru',
        ),
    ]
