# Generated by Django 4.2.26 on 2025-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_gaji_delete_gajiguru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spp',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20),
        ),
    ]
