# Generated by Django 4.2.26 on 2025-11-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_pegawai_gaji_pokok_alter_pegawai_id_pegawai'),
        ('laporan', '0002_rename_tunjangan_gaji_gaji_pokok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaji',
            name='gaji_pokok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='keterangan_tunjangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.pegawai'),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='tunjangan_jabatan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
