# Generated by Django 4.2.26 on 2025-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_alter_spp_jumlah_alter_spp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spp',
            name='tagihan',
            field=models.IntegerField(default=500000, verbose_name='Biaya SPP'),
        ),
        migrations.AlterField(
            model_name='spp',
            name='bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spp',
            name='jumlah',
            field=models.IntegerField(verbose_name='Uang Dibayar'),
        ),
        migrations.AlterField(
            model_name='spp',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
