# Generated by Django 4.2.26 on 2025-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_alter_gaji_gaji_pokok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji',
            name='nama_pegawai',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
