# Generated by Django 4.2.26 on 2025-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_spp_tagihan_alter_spp_bulan_alter_spp_jumlah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji',
            name='bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], default='Januari', max_length=20),
        ),
        migrations.AddField(
            model_name='gaji',
            name='status_transfer',
            field=models.CharField(choices=[('Belum Ditransfer', 'Belum Ditransfer'), ('Sudah Ditransfer', 'Sudah Ditransfer')], default='Belum Ditransfer', max_length=20),
        ),
    ]
