# Generated by Django 4.2.26 on 2025-12-09 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0008_siswa_user'),
        ('laporan', '0004_gaji_bulan_gaji_status_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapor',
            name='id_siswa',
        ),
        migrations.AddField(
            model_name='rapor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapor',
            name='siswa',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='rapor_siswa', to='siswa.siswa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapor',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
    ]
