# Generated by Django 4.2.26 on 2025-11-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_gaji_nama_pegawai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spp',
            old_name='id_siswa',
            new_name='siswa',
        ),
    ]
