# Generated by Django 4.2.26 on 2025-11-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
        ('laporan', '0004_gaji_nama_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spp',
            name='id_siswa',
        ),
        migrations.RemoveField(
            model_name='spp',
            name='nama',
        ),
        migrations.AddField(
            model_name='spp',
            name='siswa',
            field=models.ForeignKey(default='S001', on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spp',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='spp',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum Lunas')], max_length=10),
        ),
    ]
