# Generated by Django 4.2.26 on 2025-11-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_rename_id_siswa_spp_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('gaji_pokok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='gaji',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.pegawai'),
        ),
    ]
