# Generated by Django 5.2.8 on 2025-12-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_remove_rapor_id_siswa_rapor_created_at_rapor_siswa_and_more'),
        ('siswa', '0010_delete_spp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spp',
            name='bulan',
            field=models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')]),
        ),
        migrations.AlterField(
            model_name='spp',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_siswa', to='siswa.siswa'),
        ),
    ]
