# Generated by Django 4.2.26 on 2025-12-03 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0004_kelas'),
        ('siswa', '0003_alter_siswa_options_siswa_jurusan_siswa_kelas_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.jadwal')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.pegawai')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'ordering': ['-tanggal', 'siswa'],
                'unique_together': {('siswa', 'jadwal', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('sakit', 'Sakit'), ('izin', 'Izin'), ('alpa', 'Alpa')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.jadwal')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.pegawai')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'ordering': ['-tanggal', 'siswa'],
                'unique_together': {('siswa', 'jadwal', 'tanggal')},
            },
        ),
    ]
