# Generated by Django 4.2.26 on 2025-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='gaji_pokok',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_pegawai',
            field=models.CharField(default='P001', max_length=20),
            preserve_default=False,
        ),
    ]
