# Generated by Django 4.2.26 on 2025-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_pegawai_gaji_pokok_pegawai_id_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='gaji_pokok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='id_pegawai',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
