# Generated by Django 4.2.26 on 2025-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_jadwal_kelas_alter_pegawai_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='kelas',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
