# Generated by Django 4.2.26 on 2025-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
