# Generated by Django 4.2.26 on 2025-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='id',
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
