# Generated by Django 4.2.26 on 2025-12-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_kelas'),
        ('siswa', '0002_remove_siswa_id_alter_siswa_nis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name_plural': 'Siswa'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='admin_app.kelas'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='telepon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('lunas', 'Lunas'), ('belum', 'Belum Bayar')], default='belum', max_length=10)),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_siswa', to='siswa.siswa')),
            ],
            options={
                'verbose_name_plural': 'SPP',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
    ]
