# Generated by Django 4.2.26 on 2025-12-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_alter_siswa_options_siswa_jurusan_siswa_kelas_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas_obj',
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
