# Generated by Django 4.2.26 on 2025-12-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_jadwal_kelas'),
        ('siswa', '0004_remove_siswa_kelas_obj_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='admin_app.kelas'),
        ),
    ]
