# Generated by Django 4.2.26 on 2025-12-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_siswa_kelas_obj_alter_siswa_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='kelas_obj',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nisn',
        ),
    ]
