# Generated by Django 5.2.9 on 2025-12-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_jadwal_kelas'),
        ('siswa', '0008_siswa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('jenis', models.CharField(choices=[('UH', 'Ulangan Harian'), ('UTS', 'UTS'), ('UAS', 'UAS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_mapel', to='admin_app.jadwal')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to='siswa.siswa')),
            ],
            options={
                'verbose_name_plural': 'Nilai',
                'ordering': ['mapel__hari', 'mapel__jam_mulai'],
            },
        ),
    ]
