# Generated by Django 5.2.8 on 2025-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0009_nilai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPP',
        ),
    ]
